version: "3.8"

services:
  orderer:
    image: hyperledger/fabric-orderer:2.4.7
    hostname: hlf-orderer
    container_name: hlf-orderer
    ports:
      - "7050:7050"
    environment:
      ORDERER_GENERAL_LISTENADDRESS: "0.0.0.0"
      ORDERER_GENERAL_LISTENPORT: "7050"
      ORDERER_GENERAL_GENESISPROFILE: "SampleDevModeSolo"
      ORDERER_GENERAL_BOOTSTRAPMETHOD: "file"
      ORDERER_GENERAL_GENESISFILE: /var/hlf/genesisblock
      ORDERER_GENERAL_BOOTSTRAPFILE: /var/hlf/genesisblock
      ORDERER_OPERATIONS_LISTENADDRESS: "0.0.0.0:8080"
      ORDERER_METRICS_PROVIDER: "prometheus"
    volumes:
      - ./files/out:/var/hlf:ro
    networks:
      - dev

  peer:
    image: hyperledger/fabric-peer:2.4.7
    hostname: hlf-peer
    container_name: hlf-peer
    command:
      - peer
      - node
      - start
      - --peer-chaincodedev=true
    depends_on:
      - orderer
    ports:
      - "7051:7051"
      - "7052:7052"
    environment:
      CORE_PEER_LISTENADDRESS: "0.0.0.0:7051"
      CORE_PEER_CHAINCODELISTENADDRESS: "0.0.0.0:7052"
      CORE_OPERATIONS_LISTENADDRESS: "0.0.0.0:8080"
      CORE_METRICS_PROVIDER: "prometheus"
    volumes:
      - ./files/out:/var/hlf:ro
    networks:
      - dev

networks:
  dev:
    name: thallo-fabric